### ISSUE TITLE
Sitecore.Demo.Foundation.Accounts.Models.AccountCollectionModel is missing in xConnect

### ISSUE THREAD

**Issue by KayeeNL** [Sitecore/Sitecore.HabitatHome.Corporate#3]
**@jeanfrancoislarente, @IgorKorytko** 

Apparently when you run the build.ps1 script onto a clean 9.2 install (without SXA), we end up with a Sitecore.HabitatHome.Foundation.Accounts.Models.AccountCollectionModel, 1.0.json file into the C:\inetpub\wwwroot\habitathomecorporate_xconnect.dev.local\App_Data\Models and C:\inetpub\wwwroot\habitathomecorporate_xconnect.dev.local\App_Data\jobs\continuous\IndexWorker\App_Data\Models directories.

This one has been renamed however through the change of refactoring to nuget packages for the foundation layer. Sitecore is throwing the following exception when we have a page with a form on it, and when the Trigger a goal action fails..

6860 19:46:47 ERROR Cannot create tracker.
Exception: Sitecore.XConnect.Client.XdbModelConflictException
Message: One or more local models conflict with the xDB service layer.
 'Sitecore.Demo.Foundation.Accounts.Models.AccountCollectionModel, 1.0' does not have a remote version
Source: Sitecore.Xdb.Common.Web
   at Sitecore.Xdb.Common.Web.Synchronous.SynchronousExtensions.SuspendContextLock[TResult](Func`1 taskFactory)
   at Sitecore.XConnect.Client.XConnectSynchronousExtensions.SuspendContextLock(Func`1 taskFactory)
   at Sitecore.XConnect.Client.Configuration.SitecoreXConnectClientConfiguration.Initialize(XmlNode configNode)
   at Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert, IFactoryHelper helper)
   at Sitecore.Configuration.DefaultFactory.CreateObject(XmlNode configNode, String[] parameters, Boolean assert)
   at Sitecore.Configuration.DefaultFactory.CreateObject(String configPath, String[] parameters, Boolean assert)
   at Sitecore.XConnect.Client.Configuration.SitecoreXConnectClientConfiguration.GetClient(String clientConfigPath)
   at Sitecore.Analytics.XConnect.DataAccess.XConnectDataAdapterProvider.ExecuteWithExceptionHandling[T](Func`2 func)
   at Sitecore.Analytics.XConnect.DataAccess.XConnectDataAdapterProvider.<>c__DisplayClass15_0.<LoadContact>b__0()
   at Sitecore.Analytics.XConnect.Diagnostics.PerformanceCounters.OperationPerformanceMonitorExtensions.Monitor[T](OperationPerformanceMonitorBase monitor, Func`1 operation)
   at Sitecore.Analytics.Data.ContactRepository.LoadContact(ID contactId)
   at Sitecore.Analytics.Tracking.ContactManager.LoadContact(Guid contactId, Boolean exclusive)
   at Sitecore.Analytics.Pipelines.EnsureSessionContext.LoadContact.Process(InitializeTrackerArgs args)
   at (Object , Object )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Sitecore.Analytics.Pipelines.EnsureSessionContext.EnsureSessionContextPipeline.<>c__DisplayClass4_0.<Run>b__0()
   at Sitecore.Analytics.XConnect.Diagnostics.PerformanceCounters.OperationPerformanceMonitorExtensions.<>c__DisplayClass1_0.<Monitor>b__0()
   at Sitecore.Analytics.XConnect.Diagnostics.PerformanceCounters.OperationPerformanceMonitorExtensions.Monitor[T](OperationPerformanceMonitorBase monitor, Func`1 operation)
   at Sitecore.Analytics.DefaultTracker.EnsureSessionContext()
   at Sitecore.Analytics.Pipelines.CreateTracker.GetTracker.Process(CreateTrackerArgs args)
   at (Object , Object )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Sitecore.Analytics.Tracker.Initialize()

**The file it's expecting is called:** Sitecore.**Demo**.Foundation.Accounts.Models.AccountCollectionModel, 1.0.json instead of Sitecore.**HabitatHome**.Foundation.Accounts.Models.AccountCollectionModel, 1.0.json

and the contents of the files do differ from the file in the publish folder c:\[CHECKOUTDIR]\Sitecore.HabitatHome.Corporate\publish\App_Data\xConnectModels\Sitecore.Demo.Foundation.Accounts.Models.AccountCollectionModel, 1.0.json

Copying over the above file and removing the old one does the trick (don't forget to restart the xConnect services and iis sites).

**Comment by jflheureux** [comment]
This was fixed internally. Thanks for the report. The fix will be pushed to GitHub in the following days.
