### ISSUE TITLE
 Issue with Sync-Unicorn, Could not find type: Sitecore.Analytics.Aggregation

### ISSUE THREAD

**Issue by CosmosIsBeautiful** [Sitecore/Sitecore.HabitatHome.Corporate#6]
I do the installation of the project according to this instruction.
https://www.kayee.nl/2019/08/02/introducing-habitat-home-corporate-on-sitecore-9-2/
_(Sitecore.HabitatHome.Utilities\XP\install)_

When building the **Sitecore.Habitat Home.Corporate** project, I get the following error.

```
Sync-Unicorn
========================================
Sync Unicorn items from url: https://habitathomecorporate.dev.local/unicorn.aspx
Executing: &"C:/Projects/Sitecore.HabitatHome.Corporate/scripts/Unicorn/Sync.ps1" -secret SecretKey -url https://habitathomecorporate.dev.local/unicorn.aspx
An error occurred when executing task 'Sync-Unicorn'.
Error: One or more errors occurred.


        Could not find type: 
Sitecore.Analytics.Aggregation.XdbServicesConfigurator, 
Sitecore.Analytics.Aggregation 
[&lt;configurator type=&quot;Sitecore.Analytics.Aggregation.XdbServicesConfigurator, Sitecore.Analytics.Aggregation&quot; patch:source=&quot;Sitecore.Analytics.config&quot; xmlns:patch=&quot;http://www.sitecore.net/xmlconfig/&quot; /&gt;]


         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;}
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:pointer; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }


            Server Error in '/' Application.

             Could not find type: 
Sitecore.Analytics.Aggregation.XdbServicesConfigurator,
Sitecore.Analytics.Aggregation
[&lt;configurator type=&quot;Sitecore.Analytics.Aggregation.XdbServicesConfigurator, Sitecore.Analytics.Aggregation&quot; patch:source=&quot;Sitecore.Analytics.config&quot; xmlns:patch=&quot;http://www.sitecore.net/xmlconfig/&quot; /&gt;] 


             Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

             Exception Details: System.Configuration.ConfigurationException: Could not find type: Sitecore.Analytics.Aggregation.XdbServicesConfigurator, Sitecore.Analytics.Aggregation [&lt;configurator type=&quot;Sitecore.Analytics.Aggregation.XdbServicesConfigurator, Sitecore.Analytics.Aggregation&quot; patch:source=&quot;Sitecore.Analytics.config&quot; xmlns:patch=&quot;http://www.sitecore.net/xmlconfig/&quot; /&gt;]

            Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

            Stack Trace:

[ConfigurationException: Could not find type: Sitecore.Analytics.Aggregation.XdbServicesConfigurator, Sitecore.Analytics.Aggregation [&lt;configurator type=&quot;Sitecore.Analytics.Aggregation.XdbServicesConfigurator, Sitecore.Analytics.Aggregation&quot; patch:source=&quot;Sitecore.Analytics.config&quot; xmlns:patch=&quot;http://www.sitecore.net/xmlconfig/&quot; /&gt;]]
   Sitecore.DependencyInjection.&lt;&gt;c.&lt;GetServicesConfigurators&gt;b__2_0(XmlNode x) +261
   System.Linq.WhereSelectEnumerableIterator`2.MoveNext() +241
   Sitecore.DependencyInjection.BaseServicesConfiguratorFactory.Configure(IServiceCollection serviceCollection) +193
   Sitecore.DependencyInjection.BaseServicesConfiguratorFactory.Configure(IServiceCollection serviceCollection) +171
   Sitecore.DependencyInjection.BaseServiceProviderBuilder.ConfigureServiceCollection() +142
   Sitecore.DependencyInjection.ServiceLocator.ConfigureServiceProvider() +225
   Sitecore.DependencyInjection.ServiceLocator.get_ServiceProvider() +513
   Sitecore.DependencyInjection.SitecorePerRequestScopeModule..ctor() +13

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean&amp; canBeCached, RuntimeMethodHandleInternal&amp; ctor, Boolean&amp; bNeedSecurityCheck) +0
   System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark&amp; stackMark) +142
   System.Activator.CreateInstance(Type type, Boolean nonPublic) +107
   System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark&amp; stackMark) +1476
   System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes) +186
   System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture) +28
   System.Web.HttpRuntime.CreateNonPublicInstance(Type type, Object[] args) +80
   System.Web.HttpApplication.BuildIntegratedModuleCollection(List`1 moduleList) +234
   System.Web.HttpApplication.GetModuleCollection(IntPtr appContext) +1153
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +139
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +168
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +277
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +369

[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +532
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +111
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +724

            Version Information:&nbsp;Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.8.4075.0

c.b__2_0(XmlNode x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Sitecore.DependencyInjection.BaseServicesConfiguratorFactory.Configure(IServiceCollection serviceCollection)
   at Sitecore.DependencyInjection.BaseServicesConfiguratorFactory.Configure(IServiceCollection serviceCollection)
   at Sitecore.DependencyInjection.BaseServiceProviderBuilder.ConfigureServiceCollection()
   at Sitecore.DependencyInjection.ServiceLocator.ConfigureServiceProvider()
   at Sitecore.DependencyInjection.ServiceLocator.get_ServiceProvider()
   at Sitecore.DependencyInjection.SitecorePerRequestScopeModule..ctor()
[TargetInvocationException]: Exception has been thrown by the target of an invocation.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Web.HttpRuntime.CreateNonPublicInstance(Type type, Object[] args)
   at System.Web.HttpApplication.BuildIntegratedModuleCollection(List`1 moduleList)
   at System.Web.HttpApplication.GetModuleCollection(IntPtr appContext)
   at System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers)
   at System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context)
   at System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context)
   at System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext)
[HttpException]: Exception has been thrown by the target of an invocation.
   at System.Web.HttpRuntime.FirstRequestInit(HttpContext context)
   at System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context)
   at System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context)
-->
```

Help solve the error...

**Comment by CosmosIsBeautiful** [comment]
If you have the same error, then switch to branch **"release/9.2.0"** in both projects. 
This error occurs only for Sitecore 9.3.
